# Generated by Django 3.0.5 on 2020-06-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, choices=[('Size', 'Color'), ('Color', 'Size'), ('Size-Color', 'Size-Color')], default='Size', max_length=10),
            preserve_default=False,
        ),
    ]
