# Generated by Django 3.0.5 on 2020-06-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200601_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, choices=[('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, choices=[('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], max_length=20, verbose_name='Title'),
        ),
    ]
