# Generated by Django 3.0.5 on 2020-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200520_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Size Name'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Color Name'),
        ),
    ]
