# Generated by Django 3.0.5 on 2020-05-19 22:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_order_id', models.CharField(blank=True, max_length=120, verbose_name='Order ID')),
                ('subtotal_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Subtotal Amount')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Total Amount')),
                ('status', models.CharField(blank=True, choices=[('created', 'Created'), ('processing', 'Processing'), ('booked', 'Booked'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], max_length=50, verbose_name='Status')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('discount_code', models.CharField(blank=True, max_length=120, verbose_name='Discount Code')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=120, verbose_name='Commission Amount')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Order')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=120, verbose_name='Payment Method')),
                ('shipping_company', models.CharField(blank=True, max_length=120, verbose_name='Shipping Company')),
                ('shipping_total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('10'), max_digits=100, verbose_name='Shipping Total')),
                ('tracking_number', models.CharField(blank=True, max_length=120, verbose_name='Tracking Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Order Shipping Information')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Order Shipping Information')),
            ],
            options={
                'verbose_name': 'Order Shipping Information',
                'verbose_name_plural': 'Order Shipping Information',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShippingMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle (for status info)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Order Shipping Movement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Order Shipping Movement')),
            ],
            options={
                'verbose_name': 'Order Shipping Movement',
                'verbose_name_plural': 'Order Shipping Movements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_item_id', models.CharField(blank=True, max_length=120, verbose_name='Unique Item ID')),
                ('product_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=25, verbose_name='Product Price')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantity')),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Line Total')),
                ('refunded', models.BooleanField(default=False, verbose_name='Refunded')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Product Purchase')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Product Purchase')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Product Purchase',
                'verbose_name_plural': 'Product Purchases',
                'ordering': ['-updated_at'],
            },
        ),
    ]
