# Generated by Django 3.0.5 on 2020-06-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('vendors', '0001_initial'),
        ('carts', '0002_auto_20200601_2225'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='ordershippingmovement',
            name='shipping_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderShippingInformation', verbose_name='Shipping Information'),
        ),
        migrations.AddField(
            model_name='ordershippinginformation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='ordershippinginformation',
            name='vendor_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.VendorCustomer', verbose_name='Vendor Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.BillingProfile', verbose_name='Billing Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderShippingInformation', verbose_name='Shipping Information'),
        ),
    ]
