# Generated by Django 3.0.5 on 2020-06-01 22:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, unique=True, verbose_name='Company Name')),
                ('tax_number', models.BigIntegerField(unique=True, verbose_name='Tax Number')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Tax Office')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Phone Number')),
                ('total_purchase_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Total Purchase Amount')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Paid Amount')),
                ('unpaid_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Unpaid Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Supplier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Supplier')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active/Passive')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('address', models.TextField(verbose_name='Address Line')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ZIP / Postal Code')),
                ('district', models.CharField(max_length=30, verbose_name='District')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Turkey', max_length=30, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Address')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Address')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Delivery Address',
                'verbose_name_plural': 'Supplier Delivery Addresses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active/Passive')),
                ('address', models.TextField(verbose_name='Address Line')),
                ('zip_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ZIP / Postal Code')),
                ('district', models.CharField(max_length=30, verbose_name='District')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Turkey', max_length=30, verbose_name='Country')),
                ('billing_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=50, verbose_name='Billing Type')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
                ('tax_number', models.BigIntegerField(blank=True, default=0, verbose_name='Tax Number')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Tax Office')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date of Billing Address')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date of Billing Address')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Billing Address',
                'verbose_name_plural': 'Supplier Billing Addresses',
                'ordering': ['-updated_at'],
            },
        ),
    ]
